wordpress_id: 35
wordpress_name: Emotion
wordpress_slug: emotion
wordpress_parent: 23
title: 'Emotion'
author: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_by: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_at: 1685295407
blueprint: tag
