wordpress_id: 68
wordpress_name: Körperenergie
wordpress_slug: koerperenergie
wordpress_parent: 23
title: 'Körperenergie'
author: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_by: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_at: 1685295407
blueprint: tag
