wordpress_id: 66
wordpress_name: Neuerscheinungen
wordpress_slug: neuerscheinungen
wordpress_parent: 0
title: 'Neuerscheinungen'
author: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_by: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_at: 1685295407
blueprint: tag
