title: Test
description:
  -
    type: paragraph
    content:
      -
        type: text
        text: 'Description of this tag.'
  -
    type: paragraph
    content:
      -
        type: text
        text: 'More description of this tag...'
updated_by: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_at: 1685895409
blueprint: tag
