wordpress_id: 26
wordpress_name: Energetisierung
wordpress_slug: energetisierung-fotokarten
wordpress_parent: 23
title: 'Energetisierung'
author: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_by: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_at: 1685295407
blueprint: product_tag
