wordpress_id: 23
wordpress_name: Fotokarten
wordpress_slug: fotokarten
wordpress_parent: 22
title: 'Fotokarten'
author: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_by: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_at: 1685295407
blueprint: product_tag
