wordpress_id: 71
wordpress_name: Körperenergiewissen
wordpress_slug: koerperenergiewissen-energiekissen
wordpress_parent: 28
title: 'Körperenergiewissen'
author: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_by: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_at: 1685295407
blueprint: product_tag
