wordpress_id: 95
wordpress_name: Specials
wordpress_slug: specials
wordpress_parent: 0
title: Specials
author: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_by: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_at: 1685358307
blueprint: product_tag
