wordpress_id: 24
wordpress_name: Wandbilder
wordpress_slug: wandbilder
wordpress_parent: 22
title: 'Wandbilder'
author: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_by: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_at: 1685295407
blueprint: product_tag
