wordpress_id: 109
wordpress_name: Wirtschaft
wordpress_slug: wirtschaft
wordpress_parent: 24
title: 'Wirtschaft'
author: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_by: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_at: 1685295407
blueprint: product_tag
