wordpress_id: 40
wordpress_name: Emotion
wordpress_slug: emotion-wandbilder
wordpress_parent: 24
title: 'Emotion'
author: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_by: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_at: 1685295407
blueprint: product_category
