wordpress_id: 111
wordpress_name: Fruchtaufstriche
wordpress_slug: fruchtaufstriche
wordpress_parent: 110
title: 'Fruchtaufstriche'
author: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_by: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_at: 1685295407
blueprint: product_category
