wordpress_id: 41
wordpress_name: Gesunde Lebensführung
wordpress_slug: gesunde-lebensfuehrung-wandbilder
wordpress_parent: 24
title: 'Gesunde Lebensführung'
author: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_by: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_at: 1685295407
blueprint: product_category
