wordpress_id: 70
wordpress_name: Kinder
wordpress_slug: kinder
wordpress_parent: 23
title: 'Kinder'
author: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_by: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_at: 1685295407
blueprint: product_category
