wordpress_id: 46
wordpress_name: Körperenergie
wordpress_slug: koerperenergie-wandbilder
wordpress_parent: 24
title: 'Körperenergie'
author: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_by: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_at: 1685295407
blueprint: product_category
