wordpress_id: 89
wordpress_name: Persönlichkeit
wordpress_slug: persoenlichkeit-energiesprays
wordpress_parent: 29
title: 'Persönlichkeit'
author: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_by: 489b06db-283b-4690-a50e-8a3ba37dc968
updated_at: 1685295407
blueprint: product_category
